#
# Cut TET tables 
#  Please do not modify it by hand:
#    code automatically generated by table_generator.jl
#

empty_matrix = Array{Int64}(undef,0,0)

## Combinations for cut_tet2

const cut_tet2_nface_to_mface = Array{Array{Array{Int64,2},1},1}[
  [[empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[4 4 3 3 4; 3 1 1 2 2], 
  empty_matrix, 
  empty_matrix, ], 
  [[4 3; 3 4; 1 2], 
  [1 1; 2 4; 3 5], 
  empty_matrix, ], ] , 
 
  [[empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[2 2 4 3 3; 4 1 1 4 2], 
  empty_matrix, 
  empty_matrix, ], 
  [[2 3; 4 4; 1 2], 
  [1 4; 2 5; 3 1], 
  empty_matrix, ], ] , 
 
  [[empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[2 2 4 4 3; 4 1 1 3 1], 
  empty_matrix, 
  empty_matrix, ], 
  [[2 4; 4 3; 1 1], 
  [1 4; 2 3; 3 5], 
  empty_matrix, ], ] , 
 
  [[empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[2 2 4 4 3 3; 4 1 1 3 1 2], 
  empty_matrix, 
  empty_matrix, ], 
  [[2 4 3; 4 3 4; 1 1 2], 
  [1 4 4; 2 3 6; 3 5 1], 
  empty_matrix, ], ] , 
]

const cut_tet2_nsubface_to_nface = Array{Array{Int64,1},1}[
  [[0, 1, 2, 3, 1], ] , 
 
  [[0, 1, 2, 2, 3], ] , 
 
  [[3, 1, 0, 3, 2], ] , 
 
  [[0, 1, 0, 0, 2, 3], ] , 
]

const cut_tet2_orientation_cell_to_facet = Array{Int64,2}[
  [-1 1; 1 1; -1 -1] , 
 
  [-1 -1; 1 1; -1 1] , 
 
  [-1 -1; 1 1; -1 -1] , 
 
  [-1 -1 1; 1 1 1; -1 -1 1] , 
]

## Combinations for cut_tet3

const cut_tet3_nface_to_mface = Array{Array{Array{Int64,2},1},1}[
  [[empty_matrix, 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 4 5 4 3 2 2 2; 4 3 3 1 1 1 4 3 5], 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 5 4 2 2 2; 4 4 3 3 4 4 3; 3 1 1 1 3 5 5], 
  [1 1 2 3 7 7 8; 2 4 4 5 8 9 9; 3 5 6 6 3 1 2], 
  empty_matrix, 
  empty_matrix, ], 
  [[5 2; 4 4; 3 3; 1 5], 
  [1 7; 2 8; 3 3; 4 9; 5 1; 6 2], 
  [1 5; 2 6; 3 7; 4 1], 
  empty_matrix, ], ] , 
 
  [[empty_matrix, 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[1 1 4 1 4 2 2 4 3; 4 2 2 5 5 5 3 3 5], 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[1 1 1 4 2 2 4; 4 4 2 2 4 3 3; 2 5 5 5 3 5 5], 
  [1 1 2 3 3 7 8; 2 4 4 5 7 6 5; 3 5 6 6 8 9 9], 
  empty_matrix, 
  empty_matrix, ], 
  [[1 2; 4 4; 2 3; 5 5], 
  [1 3; 2 7; 3 8; 4 5; 5 6; 6 9], 
  [1 5; 2 4; 3 6; 4 7], 
  empty_matrix, ], ] , 
 
  [[empty_matrix, 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[1 1 4 1 4 2 5 4 3; 4 2 2 5 5 5 3 3 1], 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[1 1 1 4 5 5 4; 4 4 2 2 4 3 3; 2 5 5 5 3 1 1], 
  [1 1 2 3 5 7 8; 2 4 4 5 7 4 1; 3 5 6 6 8 9 9], 
  empty_matrix, 
  empty_matrix, ], 
  [[1 5; 4 4; 2 3; 5 1], 
  [1 5; 2 7; 3 8; 4 1; 5 4; 6 9], 
  [1 5; 2 2; 3 6; 4 7], 
  empty_matrix, ], ] , 
 
  [[empty_matrix, 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 3 5 3 2 2 4 4; 3 2 2 1 1 1 4 3 5], 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 5 3 2 2 4; 3 3 2 2 4 4 3; 2 1 1 1 3 5 5], 
  [1 1 2 3 7 7 8; 2 4 4 5 3 2 9; 3 5 6 6 8 9 1], 
  empty_matrix, 
  empty_matrix, ], 
  [[5 2; 3 4; 2 3; 1 5], 
  [1 7; 2 3; 3 8; 4 2; 5 9; 6 1], 
  [1 5; 2 6; 3 1; 4 7], 
  empty_matrix, ], ] , 
 
  [[empty_matrix, 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 3 5 3 2 5 4 4; 3 2 2 1 1 1 4 3 1], 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 5 3 5 5 4; 3 3 2 2 4 4 3; 2 1 1 1 3 1 1], 
  [1 1 2 3 7 7 8; 2 4 4 5 1 4 9; 3 5 6 6 8 9 5], 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5; 3 4; 2 3; 1 1], 
  [1 7; 2 1; 3 8; 4 4; 5 9; 6 5], 
  [1 5; 2 6; 3 2; 4 7], 
  empty_matrix, ], ] , 
 
  [[empty_matrix, 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 3 5 3 2 1 4 4; 3 2 2 1 1 1 4 2 5], 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 5 3 1 1 4; 3 3 2 2 4 4 2; 2 1 1 1 2 5 5], 
  [1 1 2 3 7 7 8; 2 4 4 5 6 4 9; 3 5 6 6 8 9 2], 
  empty_matrix, 
  empty_matrix, ], 
  [[5 1; 3 4; 2 2; 1 5], 
  [1 7; 2 6; 3 8; 4 4; 5 9; 6 2], 
  [1 5; 2 6; 3 3; 4 7], 
  empty_matrix, ], ] , 
 
  [[empty_matrix, 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[1 1 4 1 4 2 5 4 3 2; 4 2 2 5 5 5 3 3 1 3], 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[1 1 1 4 5 5 4 2 2; 4 4 2 2 4 3 3 4 3; 2 5 5 5 3 1 1 3 5], 
  [1 1 2 3 5 7 8 3 10; 2 4 4 5 7 4 1 10 6; 3 5 6 6 8 9 9 8 7], 
  empty_matrix, 
  empty_matrix, ], 
  [[1 5 2; 4 4 4; 2 3 3; 5 1 5], 
  [1 5 3; 2 7 10; 3 8 8; 4 1 5; 5 4 6; 6 9 7], 
  [1 5 8; 2 2 4; 3 6 9; 4 7 5], 
  empty_matrix, ], ] , 
 
  [[empty_matrix, 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 3 5 3 2 5 4 4 2; 3 2 2 1 1 1 4 3 1 4], 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 5 3 5 5 4 2 2; 3 3 2 2 4 4 3 4 4; 2 1 1 1 3 1 1 3 5], 
  [1 1 2 3 7 7 8 10 10; 2 4 4 5 1 4 9 3 2; 3 5 6 6 8 9 5 8 7], 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 2; 3 4 4; 2 3 3; 1 1 5], 
  [1 7 10; 2 1 3; 3 8 8; 4 4 2; 5 9 7; 6 5 1], 
  [1 5 8; 2 6 9; 3 2 1; 4 7 5], 
  empty_matrix, ], ] , 
 
  [[empty_matrix, 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 3 5 3 2 1 4 4 4; 3 2 2 1 1 1 4 2 5 3], 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 5 3 1 1 4 2 4; 3 3 2 2 4 4 2 4 3; 2 1 1 1 2 5 5 3 5], 
  [1 1 2 3 7 7 8 8 10; 2 4 4 5 6 4 9 3 9; 3 5 6 6 8 9 2 10 1], 
  empty_matrix, 
  empty_matrix, ], 
  [[5 1 2; 3 4 4; 2 2 3; 1 5 5], 
  [1 7 8; 2 6 3; 3 8 10; 4 4 9; 5 9 2; 6 2 1], 
  [1 5 8; 2 6 7; 3 3 1; 4 7 9], 
  empty_matrix, ], ] , 
 
  [[empty_matrix, 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 3 5 3 2 1 4 4 4; 3 2 2 1 1 1 4 2 5 3], 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 5 3 1 1 4 5 4; 3 3 2 2 4 4 2 4 3; 2 1 1 1 2 5 5 3 1], 
  [1 1 2 3 7 7 8 9 10; 2 4 4 5 6 4 9 1 7; 3 5 6 6 8 9 2 10 5], 
  empty_matrix, 
  empty_matrix, ], 
  [[5 1 5; 3 4 4; 2 2 3; 1 5 1], 
  [1 7 9; 2 6 1; 3 8 10; 4 4 7; 5 9 4; 6 2 5], 
  [1 5 8; 2 6 6; 3 3 2; 4 7 9], 
  empty_matrix, ], ] , 
 
  [[empty_matrix, 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 3 5 3 2 1 4 4 4; 3 2 2 1 1 1 4 2 5 3], 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ], 
  [[5 5 5 3 1 1 4 5 4 2; 3 3 2 2 4 4 2 4 3 4; 2 1 1 1 2 5 5 3 1 3], 
  [1 1 2 3 7 7 8 9 10 8; 2 4 4 5 6 4 9 1 7 3; 3 5 6 6 8 9 2 10 5 10], 
  empty_matrix, 
  empty_matrix, ], 
  [[5 1 5 2; 3 4 4 4; 2 2 3 3; 1 5 1 5], 
  [1 7 9 8; 2 6 1 3; 3 8 10 10; 4 4 7 9; 5 9 4 2; 6 2 5 1], 
  [1 5 8 10; 2 6 6 7; 3 3 2 1; 4 7 9 8], 
  empty_matrix, ], ] , 
]

const cut_tet3_nsubface_to_nface = Array{Array{Int64,1},1}[
  [[0, 0, 6, 1, 4, 2, 5, 3, 1], 
  [0, 2, 1, 3, 4, 2, 1], ] , 
 
  [[4, 1, 5, 2, 0, 0, 3, 6, 2], 
  [2, 3, 1, 0, 4, 1, 3], ] , 
 
  [[4, 1, 5, 0, 0, 3, 3, 6, 2], 
  [2, 0, 1, 4, 4, 1, 3], ] , 
 
  [[0, 0, 3, 4, 2, 1, 5, 6, 4], 
  [0, 3, 2, 1, 4, 2, 3], ] , 
 
  [[0, 5, 3, 0, 2, 1, 5, 6, 4], 
  [4, 0, 2, 1, 4, 2, 3], ] , 
 
  [[6, 0, 3, 0, 2, 1, 4, 5, 6], 
  [4, 3, 0, 1, 2, 3, 4], ] , 
 
  [[4, 1, 5, 0, 0, 0, 0, 6, 2, 3], 
  [2, 0, 1, 0, 0, 1, 3, 4, 1], ] , 
 
  [[0, 0, 3, 0, 2, 1, 0, 6, 4, 5], 
  [0, 0, 2, 1, 0, 2, 3, 4, 2], ] , 
 
  [[0, 0, 3, 0, 2, 1, 4, 5, 0, 6], 
  [0, 3, 0, 1, 2, 3, 0, 4, 3], ] , 
 
  [[0, 0, 3, 0, 2, 1, 4, 5, 0, 6], 
  [4, 0, 0, 1, 2, 0, 4, 4, 3], ] , 
 
  [[0, 0, 3, 0, 2, 1, 4, 5, 0, 6], 
  [0, 0, 0, 1, 2, 0, 0, 0, 3, 4], ] , 
]

const cut_tet3_orientation_cell_to_facet = Array{Int64,2}[
  [-1 -1; 1 1; -1 -1; 1 1] , 
 
  [-1 -1; 1 -1; -1 -1; 1 1] , 
 
  [-1 -1; 1 -1; -1 -1; 1 1] , 
 
  [-1 -1; 1 1; -1 1; 1 1] , 
 
  [-1 -1; 1 1; -1 -1; 1 1] , 
 
  [-1 -1; 1 1; -1 1; 1 1] , 
 
  [-1 -1 -1; 1 -1 -1; -1 -1 -1; 1 1 1] , 
 
  [-1 -1 -1; 1 1 1; -1 -1 1; 1 1 1] , 
 
  [-1 -1 -1; 1 1 -1; -1 1 1; 1 1 1] , 
 
  [-1 -1 -1; 1 1 -1; -1 1 -1; 1 1 1] , 
 
  [-1 -1 -1 -1; 1 1 -1 -1; -1 1 -1 1; 1 1 1 1] , 
]

