#
# Split HEX into TETs tables 
#  Please do not modify it by hand:
#    code automatically generated by table_generator.jl
#

## Connectivities for hex2_to_tet2

const hex2_to_tet2_nface_to_mface = Array{Array{Int64,2},1}[
  [[1 2 3 4], 
  empty_matrix, 
  empty_matrix, ] , 
 
  [[4 4 3 2 2; 3 1 1 4 1], 
  empty_matrix, 
  empty_matrix, ] , 
 
  [[4 2; 3 4; 1 1], 
  [1 4; 2 5; 3 2], 
  empty_matrix, ] , 
]

const hex2_to_tet2_nsubface_to_mface = Array{Int64,1}[
  [2, 0, 3, 4, 1] , 
]

const hex2_to_tet2_orientation_cell_to_facet = [-1 -1; 1 1; -1 -1]

## Connectivities for hex3_to_tet3

const hex3_to_tet3_nface_to_mface = Array{Array{Int64,2},1}[
  [[1 2 3 4 5 6 7 8], 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ] , 
 
  [[7 7 3 7 3 2 1 5 5 2 4 4 7 4 8 7 6 6 6; 3 2 2 1 1 1 5 2 7 4 3 7 8 8 2 6 5 2 8], 
  empty_matrix, 
  empty_matrix, 
  empty_matrix, ] , 
 
  [[7 7 7 3 1 1 5 2 2 4 7 7 4 7 7 6 2 6; 3 3 2 2 5 5 2 4 4 3 4 8 8 6 6 5 6 8; 2 1 1 1 2 7 7 3 7 7 8 2 2 5 2 2 8 7], 
  [1 1 2 3 7 7 8 10 10 11 12 13 14 16 16 17 18 19; 2 4 4 5 6 4 9 3 2 12 13 2 10 9 2 18 15 16; 3 5 6 6 8 9 2 11 12 1 14 15 15 17 18 8 19 13], 
  empty_matrix, 
  empty_matrix, ] , 
 
  [[7 1 2 7 7 2; 3 5 4 4 6 6; 2 2 3 8 5 8; 1 7 7 2 2 7], 
  [1 7 10 12 16 18; 2 6 3 13 9 15; 3 8 11 14 17 19; 4 4 2 10 2 16; 5 9 12 2 18 2; 6 2 1 15 8 13], 
  [1 5 8 11 14 17; 2 6 9 9 15 15; 3 3 1 12 7 12; 4 7 10 13 16 18], 
  empty_matrix, ] , 
]

const hex3_to_tet3_nsubface_to_mface = Array{Int64,1}[
  [11, 0, 0, 0, 5, 1, 9, 0, 7, 6, 2, 0, 4, 12, 0, 0, 3, 10, 8] , 
 
  [0, 5, 0, 1, 3, 5, 0, 1, 0, 4, 4, 0, 6, 2, 0, 3, 6, 2] , 
]

const hex3_to_tet3_orientation_cell_to_facet = [-1 -1 -1 -1 -1 -1; 1 1 1 -1 1 -1; -1 1 1 -1 -1 1; 1 1 1 1 1 1]

## Dictionaries

const hex_to_tet_nface_to_mface = Dict(2 => hex2_to_tet2_nface_to_mface, 3 => hex3_to_tet3_nface_to_mface, )

const hex_to_tet_nsubface_to_mface = Dict(2 => hex2_to_tet2_nsubface_to_mface, 3 => hex3_to_tet3_nsubface_to_mface, )

const hex_to_tet_orientation_cell_to_facet = Dict(2 => hex2_to_tet2_orientation_cell_to_facet, 3 => hex3_to_tet3_orientation_cell_to_facet, )

