#
#  This file includes: Look-up tables for cuts
#
#  Please do not modify it by hand:
#    code automatically generated by table_generator.jl
#

const empty_matrix = Array{Int64}(undef,0,0)

include("cut_tet_tables.jl")

include("cut_hex_tables.jl")

include("hex_to_tet_tables.jl")

